import ProductTable from "@/components/product/product-table";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Product Page",
  description: "Generated by create next app",
};
export default function Home() {
  return (
    <main className="flex min-h-screen flex-col">
      <ProductTable/>
    </main>
  );
}