import ProductSection from "@/components/marketing/products/product-section";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Products Page",
  description: "Generated by create next app",
};
export default function Home() {
  return (
    <div className="bg-white">
      <ProductSection />
    </div>
  );
}