import type { Metadata } from "next";
import "../globals.css";
import { Mulish as FontSans } from "next/font/google";
import { cn } from "@/lib/utils";
import DashboardSidebar from "@/components/dashboard/dashboard-sidebar";

const font = FontSans({
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-sans",
})

export const metadata: Metadata = {
  title: "Dashboard Page",
  description: "Generated by create next app",
};

export default function RootLayout({
                                     children,
                                   }: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <body className={cn(
      "min-h-screen bg-background font-sans antialiased bg-[#F8F8F8]",
      font.variable
    )}>
    <DashboardSidebar>
      {children}
    </DashboardSidebar>
    </body>
    </html>
  );
}
