import OrderList from "@/components/orders/order-list";
import type { Metadata } from "next";
export const metadata: Metadata = {
  title: "Order page",
  description: "Generated by create next app",
};
export default function Home() {
  return (
    <main className="flex min-h-screen flex-col">
      <OrderList/>
    </main>
  );
}