import CustomerTable from "@/components/customers/customer-table";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Customer page",
  description: "Generated by create next app",
};
export default function Home() {
  return (
    <main className="flex min-h-screen flex-col">
      <CustomerTable/>
    </main>
  );
}